### ISSUE TITLE
Todo stuff

### ISSUE THREAD

**Issue by axelkarlsson** [axelkarlsson/MomodoraRandomizer#1]
- [x] Key pickup to unlock doors
- [x] Disabling unlocking door when you have picked up from a key place but not the key itself
- [x] onDeath to Ensure that hasMissive, hasBellflower and hasPassiflora are correct if the player dies after picking the first one up and before saving. Same with hasKey stuff
- [x] onSave to ^
- [x] Text Box to show what item was received
- [x] Pause the randomizer from updating while not in game
- [x] Map levelID for every itemSource
- [x] Check so that an item is only given if the corresponding value changes to 1 and it is in the correct levelID for that pickup
- [x] Include https://docs.google.com/spreadsheets/d/1HzUkqDxlgxTf5doxWLXYY7lhv-s0krkxrdZ9kvGhn00/edit#gid=0 in the repo someway cleaner
- [x] Similar to hasKey, but for greenLeaf instead
- [x] Shops to work for all items
- [x] Hard mode logic (Boss items can be keys, backman OR garden key to access memorial park)
- [x] 1.07 support, basic mapping of old -> new address in spreadsheet and added to the randomizer
- [x] Do not randomize vitality fragments/ivory bugs unless those checkboxes are checked
- [x] Workaround for Lubella 2 softlock?
- [x] the updateItemWatchers are not correct if reloading after dying/going to memory all the time, either change them so they only count as changed when their corresponding values have increased, or run them when entering the game again to reset their basevalues to compare to when looking for what changed
- [x] going from menu to game or retrying crashes the game at times, is that due to some pointers being broken or something? Needs investigating.
- [x] Arsonist not dropping boss item if you have 2 pocket incensory in inventory (might just be one to not drop) - might need to exclude Arsonist from rando stuff
- [x] green leaf issues
- [x] cinder key door openable without getting cinder key, garden key works fine, monastery key unknown
- [x] Shop once sold the dummy item rather than actual item?
- [x] Lubella 2 softlock fix still has you as cat, can we transform to human forcibly?
